# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 14:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodslist', '0002_auto_20171015_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('commentDate', models.DateTimeField()),
                ('comment', tinymce.models.HTMLField()),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodslist.Goods')),
            ],
            options={
                'db_table': 'goodscomment',
            },
        ),
    ]
