# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areainfo',
            name='aParent',
        ),
        migrations.RemoveField(
            model_name='addrinfo',
            name='aAddressee',
        ),
        migrations.RemoveField(
            model_name='addrinfo',
            name='aCity',
        ),
        migrations.RemoveField(
            model_name='addrinfo',
            name='aDis',
        ),
        migrations.RemoveField(
            model_name='addrinfo',
            name='aPostCode',
        ),
        migrations.RemoveField(
            model_name='addrinfo',
            name='aProvince',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uAddr',
            field=models.CharField(default='空', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='uPhoneNumber',
            field=models.CharField(default='空', max_length=15),
        ),
        migrations.DeleteModel(
            name='AreaInfo',
        ),
    ]
