# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_auto_20171105_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='addrinfo',
            name='aAddressee',
            field=models.CharField(default='zoin', max_length=20),
            preserve_default=False,
        ),
    ]
