# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-15 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('buyCount', models.IntegerField(default=1)),
                ('isDelete', models.BooleanField(default=False)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('userCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='RecentSee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('extra', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo')),
            ],
            options={
                'db_table': 'recentsee',
            },
        ),
    ]
