# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercenter', '0001_initial'),
        ('goodslist', '0003_goodscomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsName', models.CharField(max_length=30)),
                ('goodsPrice', models.DecimalField(decimal_places=2, max_digits=7)),
                ('buyCount', models.IntegerField()),
                ('good_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodslist.Goods')),
            ],
            options={
                'db_table': 'orderdetail',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isFinish', models.BooleanField(default=False)),
                ('isDelete', models.BooleanField(default=False)),
                ('orderTime', models.DateTimeField()),
                ('orderNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('userOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usercenter.UserInfo')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='orders_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Orders'),
        ),
    ]
