# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='attr',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
