# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 15:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orders_attr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='attr',
            new_name='addr',
        ),
    ]
